#include "TimeGridPatchBuilder.h"

#include <algorithm>
#include <cmath>

namespace OpenTune {

namespace {

constexpr double kMinAutoSpeed = 0.8;
constexpr double kMaxAutoSpeed = 1.3;
constexpr double kSourceMatchEpsilonSeconds = 0.005;
constexpr double kIdentityOutputEpsilonSeconds = 1.0e-9;

struct ProjectedHandle {
    TimeHandle handle;
    bool autoGenerated{false};
    double desiredOutputSeconds{0.0};
};

struct RemovedHandleRecord {
    TimeHandle handle;
    bool restored{false};
};

bool isFiniteIntent(const TimeGridIntent& intent) noexcept
{
    return std::isfinite(intent.targetSourceSeconds)
        && std::isfinite(intent.desiredOutputSeconds)
        && std::isfinite(intent.confidence);
}

bool isInsideAffectedRange(double sourceSeconds, double startSeconds, double endSeconds) noexcept
{
    return sourceSeconds >= startSeconds && sourceSeconds <= endSeconds;
}

bool isApproximatelyEqual(double a, double b, double epsilon = kSourceMatchEpsilonSeconds) noexcept
{
    return std::abs(a - b) <= epsilon;
}

bool isIdentitySeedHandle(const TimeHandle& handle) noexcept
{
    return handle.kind == HandleKind::InternalOnset
        && std::abs(handle.output_seconds - handle.source_seconds) <= kIdentityOutputEpsilonSeconds;
}

bool matchesIntentSource(const TimeHandle& handle, const std::vector<TimeGridIntent>& intents) noexcept
{
    for (const auto& intent : intents) {
        if (isApproximatelyEqual(handle.source_seconds, intent.targetSourceSeconds)) {
            return true;
        }
    }
    return false;
}

bool conflictsWithExistingHandle(double sourceSeconds, const std::vector<ProjectedHandle>& handles) noexcept
{
    for (const auto& projected : handles) {
        const double left = std::min(projected.handle.source_seconds, sourceSeconds);
        const double right = std::max(projected.handle.source_seconds, sourceSeconds);
        if (!TimeGridSnapshot::hasMinimumSourceSpacing(left, right)) {
            return true;
        }
    }
    return false;
}

void sortProjectedHandles(std::vector<ProjectedHandle>& handles)
{
    std::sort(handles.begin(), handles.end(),
              [](const ProjectedHandle& a, const ProjectedHandle& b) {
                  if (a.handle.source_seconds == b.handle.source_seconds) {
                      return a.handle.output_seconds < b.handle.output_seconds;
                  }
                  return a.handle.source_seconds < b.handle.source_seconds;
              });
}

uint64_t nextHandleId(const std::vector<ProjectedHandle>& handles) noexcept
{
    uint64_t nextId = 1;
    for (const auto& projected : handles) {
        nextId = std::max(nextId, projected.handle.id + 1);
    }
    return nextId;
}

double minOutputGapForSourceSpan(double sourceSpanSeconds) noexcept
{
    return sourceSpanSeconds / kMaxAutoSpeed;
}

double maxOutputGapForSourceSpan(double sourceSpanSeconds) noexcept
{
    return sourceSpanSeconds / kMinAutoSpeed;
}

void restoreRemovedHandlesInRange(std::vector<ProjectedHandle>& handles,
                                  std::vector<RemovedHandleRecord>& removedHandles,
                                  double startSourceSeconds,
                                  double endSourceSeconds)
{
    const double left = std::min(startSourceSeconds, endSourceSeconds);
    const double right = std::max(startSourceSeconds, endSourceSeconds);

    bool restoredAny = false;
    for (auto& removed : removedHandles) {
        if (removed.restored) {
            continue;
        }
        if (removed.handle.source_seconds < left - kSourceMatchEpsilonSeconds
            || removed.handle.source_seconds > right + kSourceMatchEpsilonSeconds) {
            continue;
        }

        ProjectedHandle restored;
        restored.handle = removed.handle;
        restored.autoGenerated = false;
        restored.desiredOutputSeconds = removed.handle.output_seconds;
        handles.push_back(std::move(restored));
        removed.restored = true;
        restoredAny = true;
    }

    if (restoredAny) {
        sortProjectedHandles(handles);
    }
}

bool projectRun(std::vector<ProjectedHandle>& handles,
                size_t leftFixedIndex,
                size_t rightFixedIndex,
                juce::String& outError)
{
    if (leftFixedIndex >= rightFixedIndex || rightFixedIndex >= handles.size()) {
        outError = "AUTO Ref TimeGrid run projection received invalid boundaries";
        return false;
    }
    if (handles[leftFixedIndex].autoGenerated || handles[rightFixedIndex].autoGenerated) {
        outError = "AUTO Ref TimeGrid run projection requires fixed boundary handles";
        return false;
    }

    std::vector<double> low(handles.size(), 0.0);
    std::vector<double> high(handles.size(), 0.0);
    low[leftFixedIndex] = handles[leftFixedIndex].handle.output_seconds;
    high[leftFixedIndex] = handles[leftFixedIndex].handle.output_seconds;

    for (size_t i = leftFixedIndex + 1; i <= rightFixedIndex; ++i) {
        const double sourceSpan = handles[i].handle.source_seconds - handles[i - 1].handle.source_seconds;
        const double minGap = minOutputGapForSourceSpan(sourceSpan);
        const double maxGap = maxOutputGapForSourceSpan(sourceSpan);

        low[i] = low[i - 1] + minGap;
        high[i] = high[i - 1] + maxGap;

        if (!handles[i].autoGenerated) {
            const double fixedOutput = handles[i].handle.output_seconds;
            low[i] = std::max(low[i], fixedOutput);
            high[i] = std::min(high[i], fixedOutput);
        }

        if (low[i] > high[i] + 1.0e-9) {
            outError = "AUTO Ref TimeGrid run exceeds local 0.8x~1.3x speed window";
            return false;
        }
    }

    for (size_t i = rightFixedIndex; i-- > leftFixedIndex + 1;) {
        const double sourceSpan = handles[i + 1].handle.source_seconds - handles[i].handle.source_seconds;
        const double minGap = minOutputGapForSourceSpan(sourceSpan);
        const double maxGap = maxOutputGapForSourceSpan(sourceSpan);
        const double feasibleLow = std::max(low[i], handles[i + 1].handle.output_seconds - maxGap);
        const double feasibleHigh = std::min(high[i], handles[i + 1].handle.output_seconds - minGap);
        if (feasibleLow > feasibleHigh + 1.0e-9) {
            outError = "AUTO Ref TimeGrid run cannot be saturated inside local speed window";
            return false;
        }

        if (handles[i].autoGenerated) {
            handles[i].handle.output_seconds =
                juce::jlimit(feasibleLow, feasibleHigh, handles[i].desiredOutputSeconds);
        } else {
            const double fixedOutput = handles[i].handle.output_seconds;
            if (fixedOutput < feasibleLow - 1.0e-9 || fixedOutput > feasibleHigh + 1.0e-9) {
                outError = "AUTO Ref TimeGrid fixed handle prevents a feasible local speed projection";
                return false;
            }
        }
    }

    return true;
}

bool projectAutoHandles(std::vector<ProjectedHandle>& handles,
                        std::vector<RemovedHandleRecord>& removedHandles,
                        juce::String& outError)
{
    size_t index = 0;
    while (index < handles.size()) {
        if (!handles[index].autoGenerated) {
            ++index;
            continue;
        }

        const size_t runStart = index;
        while (index < handles.size() && handles[index].autoGenerated) {
            ++index;
        }
        const size_t runEnd = index - 1;

        auto rollbackRun = [&](double restoreStartSource,
                               double restoreEndSource,
                               const juce::String& runError) {
            handles.erase(handles.begin() + static_cast<std::ptrdiff_t>(runStart),
                          handles.begin() + static_cast<std::ptrdiff_t>(runEnd + 1));
            restoreRemovedHandlesInRange(handles,
                                         removedHandles,
                                         restoreStartSource,
                                         restoreEndSource);
            outError = runError;
            index = 0;
        };

        if (runStart == 0 || index >= handles.size()) {
            rollbackRun(handles[runStart].handle.source_seconds,
                        handles[runEnd].handle.source_seconds,
                        "AUTO Ref TimeGrid run must stay bounded by fixed handles");
            continue;
        }

        juce::String runError;
        if (!projectRun(handles, runStart - 1, runEnd + 1, runError)) {
            rollbackRun(handles[runStart - 1].handle.source_seconds,
                        handles[runEnd + 1].handle.source_seconds,
                        runError);
        }
    }

    return true;
}

bool sameHandles(const std::vector<TimeHandle>& left, const std::vector<TimeHandle>& right) noexcept
{
    if (left.size() != right.size()) {
        return false;
    }

    for (size_t i = 0; i < left.size(); ++i) {
        const auto& a = left[i];
        const auto& b = right[i];
        if (a.id != b.id
            || a.source_seconds != b.source_seconds
            || a.output_seconds != b.output_seconds
            || a.kind != b.kind
            || a.locked != b.locked
            || a.confidence != b.confidence) {
            return false;
        }
    }

    return true;
}

} // namespace

TimeGridPatchResult TimeGridPatchBuilder::build(const TimeGridPatchRequest& request)
{
    TimeGridPatchResult result;

    if (request.before == nullptr) {
        result.diagnostic = "AUTO Ref TimeGrid patch requires a source grid";
        return result;
    }

    const double affectedStart = std::min(request.affectedSourceStartSeconds,
                                          request.affectedSourceEndSeconds);
    const double affectedEnd = std::max(request.affectedSourceStartSeconds,
                                        request.affectedSourceEndSeconds);
    if (!std::isfinite(affectedStart) || !std::isfinite(affectedEnd)
        || affectedEnd <= affectedStart) {
        result.diagnostic = "AUTO Ref TimeGrid patch has an invalid affected source range";
        return result;
    }

    const double duration = request.before->totalDurationSeconds();
    std::vector<TimeGridIntent> intents = request.intents;
    std::sort(intents.begin(), intents.end(),
              [](const TimeGridIntent& a, const TimeGridIntent& b) {
                  return a.targetSourceSeconds < b.targetSourceSeconds;
              });

    std::vector<ProjectedHandle> handles;
    handles.reserve(request.before->handles().size() + intents.size());
    std::vector<RemovedHandleRecord> removedHandles;
    removedHandles.reserve(request.before->handles().size());

    for (const auto& handle : request.before->handles()) {
        const bool removeReferenceAuto = handle.kind == HandleKind::ReferenceAuto
                                      && handle.source_seconds > affectedStart
                                      && handle.source_seconds < affectedEnd;
        const bool replaceIdentitySeed = isIdentitySeedHandle(handle)
                                      && handle.source_seconds > affectedStart
                                      && handle.source_seconds < affectedEnd
                                      && matchesIntentSource(handle, intents);
        if (removeReferenceAuto || replaceIdentitySeed) {
            removedHandles.push_back(RemovedHandleRecord{handle, false});
            continue;
        }

        ProjectedHandle projected;
        projected.handle = handle;
        projected.autoGenerated = false;
        projected.desiredOutputSeconds = handle.output_seconds;
        handles.push_back(std::move(projected));
    }

    uint64_t nextId = nextHandleId(handles);
    for (const auto& intent : intents) {
        if (!isFiniteIntent(intent)) {
            result.diagnostic = "AUTO Ref TimeGrid intent contains non-finite values";
            return result;
        }
        if (intent.targetSourceSeconds <= 0.0 || intent.targetSourceSeconds >= duration
            || intent.desiredOutputSeconds <= 0.0 || intent.desiredOutputSeconds >= duration) {
            result.diagnostic = "AUTO Ref TimeGrid intent lies outside target duration";
            return result;
        }
        if (!isInsideAffectedRange(intent.targetSourceSeconds, affectedStart, affectedEnd)) {
            result.diagnostic = "AUTO Ref TimeGrid intent lies outside affected source range";
            return result;
        }
        if (conflictsWithExistingHandle(intent.targetSourceSeconds, handles)) {
            continue;
        }

        ProjectedHandle projected;
        projected.autoGenerated = true;
        projected.desiredOutputSeconds = intent.desiredOutputSeconds;
        projected.handle.id = nextId++;
        projected.handle.source_seconds = intent.targetSourceSeconds;
        projected.handle.output_seconds = intent.desiredOutputSeconds;
        projected.handle.kind = HandleKind::ReferenceAuto;
        projected.handle.locked = false;
        projected.handle.confidence = intent.confidence >= 0.75f ? Confidence::High : Confidence::Default;
        handles.push_back(std::move(projected));
    }

    sortProjectedHandles(handles);

    juce::String projectionNote;
    projectAutoHandles(handles, removedHandles, projectionNote);

    std::vector<TimeHandle> finalHandles;
    finalHandles.reserve(handles.size());
    for (const auto& projected : handles) {
        finalHandles.push_back(projected.handle);
    }

    juce::String validationError;
    if (!TimeGridSnapshot::validate(finalHandles, validationError)) {
        result.diagnostic = validationError;
        return result;
    }

    if (sameHandles(finalHandles, request.before->handles())) {
        result.after = request.before;
        result.success = true;
        result.diagnostic = projectionNote;
        return result;
    }

    result.after = TimeGridSnapshot::makeFromHandles(std::move(finalHandles),
                                                     request.before->revision() + 1);
    if (result.after == nullptr) {
        result.diagnostic = "AUTO Ref produced an invalid TimeGrid";
        return result;
    }

    result.success = true;
    result.diagnostic = projectionNote;
    return result;
}

} // namespace OpenTune
